export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST";
export const GET_PRODUCT_FAILURE="GET_PRODUCT_FAILURE";
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";



export const SORT_PRODUCT_REQUEST='SORT_PRODUCT_REQUEST';
export const SORT_PRODUCT_FAILURE="SORT_PRODUCT_FAILURE";
export const SORT_PRODUCT_SUCCESS="SORT_PRODUCT_SUCCESS";
