export const personalPopularCategories = [
    {
      title: "Hair Care",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/jzhrhsw9tvdfxdymzx1i.png",
    },
    {
      title: "Oral Care",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/mudcqavrdndwx3xkgdhd.png",
    },
    {
      title: "Healthcare Devices",
      img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/fbigjgxv2wquqqb3galn.png",
    },
    {
      title: "Elderly Care",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/xmlgiis0j0b3c56sgdfa.png",
    },
    {
      title: "Sexual Wellness",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/hnkvhccweea1wzetxcwj.png",
    },
    {
      title: "Skin Care",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/zywfnyjix46lsbx9zjt3.png",
    },
    {
      title: "Baby Care",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/f13ns7bu6ctzkoaovukq.png",
    },
    {
      title: "Women Care",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/cn00oakynuc1g1usorxm.png",
    },
    {
      title: "Men Care",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/zlj6fgclzhv0oc66dij0.png",
    },
  ];




  export const topSellingProducts = [
    {
      link: "https://www.1mg.com/otc/dettol-original-bathing-soap-bar-125gm-each-buy-4-get-1-free-otc587797",
      img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/peqt9rbamkoiajvdpew9/dettol-original-bathing-soap-bar-125gm-each-buy-4-get-1-free.jpg",
      name: "Dettol Original Bathing Soap Bar 125gm Each",
      qty: "1 Combo pack of 5 soaps",
      strikePrice: "322",
      discount: "3% off",
      price: "312",
    },
    {
      link: "https://www.1mg.com/otc/cetaphil-gentle-skin-cleanser-dry-to-normal-sensitive-skin-otc534955",
      img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/uhhnh0i8zxkpwqg0hoer/cetaphil-gentle-skin-cleanser-dry-to-normal-sensitive-skin.jpg",
      name: "Cetaphil Gentle Skin Cleanser Dry to Normal, Sensitive Skin",
      qty: "1 Pump bottle of 1000 ml Cleanser",
      strikePrice: "1245",
      discount: "5% off",
      price: "1182",
    },
    {
      link: "https://www.1mg.com/otc/scalpe-expert-anti-dandruff-shampoo-otc339199",
      img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/tri1qxerh611gi5u6gdv/scalpe-expert-anti-dandruff-shampoo.jpg",
      name: "Baidyanath Kesari Kalp Royal Chyawanprash Promotes Vitality, Strength & Stamina",
      qty: "1 Bottle of 75 ml Shampoo",
      strikePrice: "280",
      discount: "20% off",
      price: "202",
    },
    {
      link: "https://www.1mg.com/otc/friends-premium-adult-dry-pants-medium-otc635871",
      img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/sjbhlpjner4thvjdrkdp/friends-premium-adult-dry-pants-medium.jpg",
      name: "Friends Premium Adult Dry Pants Medium",
      qty: "1 Packet of 10 diapers",
      strikePrice: "550",
      discount: "5% off",
      price: "523",
    },
    {
      link: "https://www.1mg.com/otc/ahaglow-advanced-skin-rejuvenating-face-wash-otc525352",
      img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/tmcl9ndskbiezitxdy5y/ahaglow-advanced-skin-rejuvenating-face-wash.jpg",
      name: "Ahaglow Advanced Skin Rejuvenating Face Wash",
      qty: "1 Tube of 200 gm Face Wash",
      strikePrice: "710",
      discount: "6% off",
      price: "667",
    },
    {
      link: "https://www.1mg.com/otc/la-shield-fisico-matte-spf-50-sunscreen-gel-otc497461",
      img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/nngfb0pklqag3bymciuu/la-shield-fisico-matte-spf-50-sunscreen-gel.jpg",
      name: "La Shield Fisico Matte SPF 50 Sunscreen Gel",
      qty: "1 Tube of 50 gm Gel",
      strikePrice: "225",
      discount: "15% off",
      price: "191",
    },
    {
      link: "https://www.1mg.com/otc/baidyanath-kesari-kalp-royal-chyawanprash-promotes-vitality-strength-stamina-otc388303",
      img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/sotrimm6r6qrtbt5qtmw.jpg",
      name: "Baidyanath Kesari Kalp Royal Chyawanprash Promotes Vitality, Strength & Stamina",
      qty: "jar of 500 gm Paste",
      strikePrice: "650",
      discount: "15% off",
      price: "553",
    },
    {
      link: "https://www.1mg.com/otc/mamaearth-onion-shampoo-otc550078",
      img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/i5kbl7bek1cueqvvcfqu/mamaearth-onion-shampoo.jpg",
      name: "Mamaearth Onion Shampoo",
      qty: "1 Pump bottle of 250 ml Shampoo",
      strikePrice: "349",
      discount: "5% off",
      price: "331",
    },
    {
      link: "https://www.1mg.com/otc/mcaffeine-naked-raw-coffee-body-scrub-otc689829",
      img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/w6b53anuxkm01myxy4aa/mcaffeine-naked-raw-coffee-body-scrub.jpg",
      name: "Baidyanath Vansaar Aloe Vera Juice",
      qty: "1 Jar of 100 gm Scrub",
      strikePrice: "449",
      discount: "12% off",
      price: "395",
    },
    {
      link: "https://www.1mg.com/otc/plum-green-tea-renewed-clarity-night-gel-otc596730",
      img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/eqmjait4j3agzsdeus3r/plum-green-tea-renewed-clarity-night-gel.jpg",
      name: "Plum Green Tea Renewed Clarity Night Gel",
      qty: "1 Jar of 50 ml Gel",
      strikePrice: "575",
      discount: "25% off",
      price: "431",
    },
  ];
  


  
export const PersonalFeaturedBrands = [
    {
      title: "Face Wash",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/ytnsdhr7hemetc3wzjxv.png",
    },
    {
      title: "Body Lotion",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/aomifv58g7cciam908ii.png",
    },
    {
      title: "Oral Care",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/hw3sftezpno4ilzbhygh.png",
    },
    {
      title: "Ayurveda Care",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/grx88e13sxd1vodqlk9q.png",
    },
    {
      title: "Hair Oil",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/d1rc6avkhhl6at7mzpu2.png",
    },
    {
      title: "Shampoo",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/lscmv9csdohicmkshemn.png",
    },
    {
      title: "Oral Care",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/hw3sftezpno4ilzbhygh.png",
    },
    {
      title: "Ayurveda Care",
      img: "https://onemg.gumlet.io/f_auto,w_150,c_fit,a_ignore,h_150,q_auto/grx88e13sxd1vodqlk9q.png",
    },
  ];

  export const PAllProducts = [
    {
      id: 1,
      link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
      img: "https://onemg.gumlet.io/images/q_auto,h_150,f_auto,c_fit,w_150/rd7ixqu9ed5qtggnflt9/ketoscalp-shampoo.jpg",
      name: "Ketoscalp Shampoo",
      qty: "1 Bottle 100 ml in 1 bottle",
      strikePrice: "114",
      discount: "35% off",
      price: "190",
    },
    {
      id: 2,
      link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
      img: "https://onemg.gumlet.io/images/q_auto,h_150,f_auto,c_fit,w_150/cropped/x20rkmrxghxwbdko3a0n/orasore-mouth-ulcer-relief-gel.jpg",
      name: "Orasore Mouth Ulcer Relief Gel",
      qty: "1 Bottle of 500 pellets",
      strikePrice: "78",
      discount: "32% off",
      price: "53",
    }, 
      {
        link: "https://www.1mg.com/otc/dettol-original-bathing-soap-bar-125gm-each-buy-4-get-1-free-otc587797",
        img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/peqt9rbamkoiajvdpew9/dettol-original-bathing-soap-bar-125gm-each-buy-4-get-1-free.jpg",
        name: "Dettol Original Bathing Soap Bar 125gm Each",
        qty: "1 Combo pack of 5 soaps",
        strikePrice: "322",
        discount: "3% off",
        price: "312",
      },
      {
        link: "https://www.1mg.com/otc/cetaphil-gentle-skin-cleanser-dry-to-normal-sensitive-skin-otc534955",
        img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/uhhnh0i8zxkpwqg0hoer/cetaphil-gentle-skin-cleanser-dry-to-normal-sensitive-skin.jpg",
        name: "Cetaphil Gentle Skin Cleanser Dry to Normal, Sensitive Skin",
        qty: "1 Pump bottle of 1000 ml Cleanser",
        strikePrice: "1245",
        discount: "5% off",
        price: "1182",
      },
      {
        link: "https://www.1mg.com/otc/scalpe-expert-anti-dandruff-shampoo-otc339199",
        img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/tri1qxerh611gi5u6gdv/scalpe-expert-anti-dandruff-shampoo.jpg",
        name: "Baidyanath Kesari Kalp Royal Chyawanprash Promotes Vitality, Strength & Stamina",
        qty: "1 Bottle of 75 ml Shampoo",
        strikePrice: "280",
        discount: "20% off",
        price: "202",
      },
      {
        link: "https://www.1mg.com/otc/friends-premium-adult-dry-pants-medium-otc635871",
        img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/sjbhlpjner4thvjdrkdp/friends-premium-adult-dry-pants-medium.jpg",
        name: "Friends Premium Adult Dry Pants Medium",
        qty: "1 Packet of 10 diapers",
        strikePrice: "550",
        discount: "5% off",
        price: "523",
      },
      {
        link: "https://www.1mg.com/otc/ahaglow-advanced-skin-rejuvenating-face-wash-otc525352",
        img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/tmcl9ndskbiezitxdy5y/ahaglow-advanced-skin-rejuvenating-face-wash.jpg",
        name: "Ahaglow Advanced Skin Rejuvenating Face Wash",
        qty: "1 Tube of 200 gm Face Wash",
        strikePrice: "710",
        discount: "6% off",
        price: "667",
      },
      {
        link: "https://www.1mg.com/otc/la-shield-fisico-matte-spf-50-sunscreen-gel-otc497461",
        img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/nngfb0pklqag3bymciuu/la-shield-fisico-matte-spf-50-sunscreen-gel.jpg",
        name: "La Shield Fisico Matte SPF 50 Sunscreen Gel",
        qty: "1 Tube of 50 gm Gel",
        strikePrice: "225",
        discount: "15% off",
        price: "191",
      },
      {
        link: "https://www.1mg.com/otc/baidyanath-kesari-kalp-royal-chyawanprash-promotes-vitality-strength-stamina-otc388303",
        img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/sotrimm6r6qrtbt5qtmw.jpg",
        name: "Baidyanath Kesari Kalp Royal Chyawanprash Promotes Vitality, Strength & Stamina",
        qty: "jar of 500 gm Paste",
        strikePrice: "650",
        discount: "15% off",
        price: "553",
      },
      {
        link: "https://www.1mg.com/otc/mamaearth-onion-shampoo-otc550078",
        img: "https://onemg.gumlet.io/images/q_auto,h_150,f_auto,c_fit,w_150/a4d57964e30a4f549cd7e641c0e6041b/prega-news-pregnancy-test-kit.jpg",
        name: "Prega News Pregnancy Test Kit",
        qty: "2 Packets (minimum) of1 Test Kit",
        strikePrice: "60",
        discount: "5% off",
        price: "55",
      },
      {
        link: "https://www.1mg.com/otc/mcaffeine-naked-raw-coffee-body-scrub-otc689829",
        img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/w6b53anuxkm01myxy4aa/mcaffeine-naked-raw-coffee-body-scrub.jpg",
        name: "Baidyanath Vansaar Aloe Vera Juice",
        qty: "1 Jar of 100 gm Scrub",
        strikePrice: "449",
        discount: "12% off",
        price: "395",
      },
      {
        link: "https://www.1mg.com/otc/plum-green-tea-renewed-clarity-night-gel-otc596730",
        img: "https://onemg.gumlet.io/images/w_150,f_auto,c_fit,h_150,q_auto/eqmjait4j3agzsdeus3r/plum-green-tea-renewed-clarity-night-gel.jpg",
        name: "Plum Green Tea Renewed Clarity Night Gel",
        qty: "1 Jar of 50 ml Gel",
        strikePrice: "575",
        discount: "25% off",
        price: "431",
      },
    {
      id: 3,
      link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
      img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/iujsngvmj0nja3ru0xk9/health-veda-organics-skin-radiance-collagen-builder-veg-capsule.jpg",
      name: "Health Veda Organics Skin Radiance Collagen Builder Veg Capsule",
      qty: "1 Bottle of 500 pellets",
      strikePrice: "799",
      discount: "48% off",
      price: "410",
    }, 
    {
      id: 4,
      link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
      img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/2b1dea512d474ab48100f1969cb9f6e8/tata-1mg-milk-thistle-veg-capsule-for-liver-detox-70-silymarin-with-dandelion-ginger-supports-liver-detox-prevents-fatty-liver.jpg",
      name: "Tata 1mg Milk Thistle Veg Capsule for Liver Detox,Supports Liver Detox ",
      qty: "1 Bottle of 500 pellets",
      strikePrice: "845",
      discount: "48% off",
      price: "425",
    },
  
  
    {
      id: 3,
      link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
      img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/iujsngvmj0nja3ru0xk9/health-veda-organics-skin-radiance-collagen-builder-veg-capsule.jpg",
      name: "Health Veda Organics Skin Radiance Collagen Builder Veg Capsule",
      qty: "1 Bottle of 500 pellets",
      strikePrice: "799",
      discount: "48% off",
      price: "410",
    }, 
    {
      id: 4,
      link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
      img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/2b1dea512d474ab48100f1969cb9f6e8/tata-1mg-milk-thistle-veg-capsule-for-liver-detox-70-silymarin-with-dandelion-ginger-supports-liver-detox-prevents-fatty-liver.jpg",
      name: "Tata 1mg Milk Thistle Veg Capsule for Liver Detox",
      qty: "1 Bottle of 500 pellets",
      strikePrice: "845",
      discount: "48% off",
      price: "425",
    },
  
    {
      id: 5,
      link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
      img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/cropped/qslig3kow84ahcdydboo/avene-physiolift-eyes.png",
      name: "Avene Physiolift Eyes",
      qty: "1 Bottle of 500 creame",
      strikePrice: "845",
      discount: "48% off",
      price: "425",
    },
  
    {
      id: 6,
      link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
      img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/uwq2dwmpqikf9ei3hok5/vaamveda-gorgeous-biotin-tablets-for-hair-growth-with-keratin.jpg",
      name: "Vaamveda Gorgeous Biotin Tablets",
      qty: "1 Bottle of 500 creame",
      strikePrice: "845",
      discount: "48% off",
      price: "425",
    },
    {
      id: 7,
      link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
      img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/cropped/m7ywndnc6att5k6bc8cs/himalaya-liv.-52-ds-tablet.jpg",
      name: "Himalaya Liv. 52 DS Tablet",
      qty: "1 Bottle of 500 creame",
      strikePrice: "845",
      discount: "48% off",
      price: "425",
    },
    {
      id: 8,
      link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
      img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/cropped/yri5iww1npeaibjz6i7y/healthvit-beta-sitosterol-160mg-capsule.jpg",
      name: "HealthVit Beta Sitosterol 160mg Capsule",
      qty: "1 Bottle of 500 creame",
      strikePrice: "845",
      discount: "48% off",
      price: "425",
    },
    {
      id: 9,
      link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
      img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/2b1dea512d474ab48100f1969cb9f6e8/tata-1mg-milk-thistle-veg-capsule-for-liver-detox-70-silymarin-with-dandelion-ginger-supports-liver-detox-prevents-fatty-liver.jpg",
      name: "Tata 1mg Milk Thistle Veg Capsule for Liver Detox",
      qty: "1 Bottle of 500 pellets",
      strikePrice: "845",
      discount: "48% off",
      price: "425",
    },
    {
      id: 10,
      link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
      img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/dj9v8xuxcpfoseulq96n/tata-1mg-coq-10-coenzyme-10-capsules-for-heart-health.jpg",
      name: "Tata 1mg CoQ 10 (Coenzyme 10) Capsules for Heart Health",
      qty: "bottle of 10 gm Tablet",
      strikePrice: "995",
      discount: "35% off",
      price: "444",
    },
    {
      id: 11,
      link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
      img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/cropped/m7ywndnc6att5k6bc8cs/himalaya-liv.-52-ds-tablet.jpg",
      name: "Himalaya Liv. 52 DS Tablet",
      qty: "1 Bottle of 500 creame",
      strikePrice: "845",
      discount: "48% off",
      price: "425",
    },
  ]