export const Shopbyhealthconcerns = [
  {
    title: "Diabetes Care",
    img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/c2a0598f-483c-48ff-9783-71e402aa28d3.png"
  },
  {
    title: "Cardiac Care",
    img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/ab1da5f4-c074-47d2-b278-a5fbd2c93f1f.png",
  },
  {
    title: "Stomach Care",
    img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/18e90e64-9e8c-47c5-ae33-508903429450.png"
  },
  {
    title: "Liver Care",
    img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/14f0bebe-6220-4ac7-b4bb-c5b425975af3.png"
  },
  {
    title: "Boen,joint & Muscle care",
    img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/ba975795-98dc-4cd8-8b55-3c20230d70e3.png"
  },
  {
    title: "Kidney Care",
    img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/555f6a24-3e20-41ee-a03b-e3dbda183392.png"
  },
  {
    title: "Pain relief",
    img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/5fa692ad-6647-4db5-9cb4-eb0bd9111331.png"
  },
  {
    title: "Respiratory Care",
    img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/4a788b46-97f3-460e-afb6-428368f779ee.png"
  },
  {
    title: "Eye Care",
    img: "https://onemg.gumlet.io/a_ignore,w_150,h_150,c_fit,q_auto,f_auto/631e3dca-3d5b-49f8-832b-8341ec4784e7.png"
  },

]

export const topSellingProducts = [
  {
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/tlfgbykcqbhn5jieozfj.jpg",
    name: "Baidyanath Kamini Vidrawan Ras Keshar Yukta Tablet",
    qty: "bottle of 10 gm Tablet",
    strikePrice: "1698",
    discount: "20% off",
    price: "1358",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vansaar-isabgol-psyllium-husk-powder-otc371516",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/hb574zgh9ypwmpel9mxz.jpg",
    name: "Baidyanath Vansaar Isabgol Psyllium Husk Powder",
    qty: "box of 200 gm Powder",
    strikePrice: "225",
    discount: "14% off",
    price: "193",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-kesari-kalp-royal-chyawanprash-promotes-vitality-strength-stamina-otc325914",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/wxcyaombrajpkyvcvnrm.jpg",
    name: "Baidyanath Kesari Kalp Royal Chyawanprash Promotes Vitality, Strength & Stamina",
    qty: "jar of 1 kg Paste",
    strikePrice: "740",
    discount: "30% off",
    price: "518",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-kanchnar-guggulu-tablet-otc325867",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/zd02vxwzldjojodryrbk.jpg",
    name: "Baidyanath Kanchnar Guggulu Tablet",
    qty: "bottle of 80 tablets",
    strikePrice: "140",
    discount: "14% off",
    price: "120",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-chyawanprash-special-immunity-booster-for-omniprotection-with-madhu-free-50gm-otc698062",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/r4q79nrsaa1tfaxfvbn7.jpg",
    name: "Baidyanath Chyawanprash Special Immunity Booster ",
    qty: "jar of 950 gm Paste",
    strikePrice: "395",
    discount: "15% off",
    price: "336",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vita-ex-massage-oil-otc349340",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/cropped/yrlsaq5pmpkpmu0u0cqd.jpg",
    name: "Baidyanath Vita EX Massage Oil",
    qty: "bottle of 15 ml Oil",
    strikePrice: "225",
    discount: "15% off",
    price: "191",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-kesari-kalp-royal-chyawanprash-promotes-vitality-strength-stamina-otc388303",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/sotrimm6r6qrtbt5qtmw.jpg",
    name: "Baidyanath Kesari Kalp Royal Chyawanprash Promotes Vitality, Strength & Stamina",
    qty: "jar of 500 gm Paste",
    strikePrice: "420",
    discount: "14% off",
    price: "361",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-chyawan-vit-sugarfree-chyawanprash-for-boosting-immunity-otc337211",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/cropped/crqoyzk9fbxvdpdk2efj.png",
    name: "Baidyanath Chyawan-Vit Sugarfree Chyawanprash for Boosting Immunity",
    qty: "jar of 500 gm Paste",
    strikePrice: "225",
    discount: "15% off",
    price: "191",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vansaar-aloe-vera-juice-otc349149",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/lc0ysjyol0asm5eeoxut.jpg",
    name: "Baidyanath Vansaar Aloe Vera Juice",
    qty: "bottle of 1 Ltr Juice",
    strikePrice: "265",
    discount: "35% off",
    price: "172",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vita-ex-gold-capsule-for-vitality-stamina-otc323951",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/ogypzm1jrh5y0gislnwm.jpg",
    name: "Baidyanath Vita-Ex Gold Capsule for Vitality & Stamina",
    qty: "bottle of 20 capsules",
    strikePrice: "475",
    discount: "15% off",
    price: "404",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vansaar-shilajit-resin-otc671424",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/ttujayukq6mdk95t1aob.jpg",
    name: "Baidyanath Vansaar Shilajit Resin",
    qty: "bottle of 15 gm Pack",
    strikePrice: "1499",
    discount: "15% off",
    price: "1274",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-chitrakadi-bati-tablet-otc327001",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/cropped/zrphzczzrwe4o6hnqmqc.png",
    name: "Baidyanath Chitrakadi Bati Tablet",
    qty: "bottle of 80 tablets",
    strikePrice: "94",
    discount: "14% off",
    price: "81",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vansaar-isabgol-psyllium-husk-powder-otc497819",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/dxxwizplopbwahvbcbb2.jpg",
    name: "Baidyanath Vansaar Isabgol Psyllium Husk Powder",
    qty: "box of 100 gm Powder",
    strikePrice: "120",
    discount: "15% off",
    price: "102",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vansaar-triphala-juice-natural-herbal-laxative-otc349184",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/foeocdhjfl51ub5wafmg.jpg",
    name: "Baidyanath Vansaar Triphala Juice Natural Herbal Laxative",
    qty: "bottle of 1 Ltr Juice",
    strikePrice: "265",
    discount: "13% off",
    price: "230",
  },
];



export const AllProducts = [
  {
    id: 1,
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/dj9v8xuxcpfoseulq96n/tata-1mg-coq-10-coenzyme-10-capsules-for-heart-health.jpg",
    name: "Tata 1mg CoQ 10 (Coenzyme 10) Capsules for Heart Health",
    qty: "bottle of 10 gm Tablet",
    strikePrice: "995",
    discount: "35% off",
    price: "444",
  },
  {
    id: 2,
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/cropped/bpgstknem0udqzp9p4dm/sugar-free-gold-low-calorie-sweetener.jpg",
    name: "Sugar Free Gold Low Calorie Sweetener",
    qty: "1 Bottle of 500 pellets",
    strikePrice: "285",
    discount: "15% off",
    price: "257",
  }, 
  {
    id: 3,
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/iujsngvmj0nja3ru0xk9/health-veda-organics-skin-radiance-collagen-builder-veg-capsule.jpg",
    name: "Health Veda Organics Skin Radiance Collagen Builder Veg Capsule",
    qty: "1 Bottle of 500 pellets",
    strikePrice: "799",
    discount: "48% off",
    price: "410",
  }, 
  {
    id: 4,
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/2b1dea512d474ab48100f1969cb9f6e8/tata-1mg-milk-thistle-veg-capsule-for-liver-detox-70-silymarin-with-dandelion-ginger-supports-liver-detox-prevents-fatty-liver.jpg",
    name: "Tata 1mg Milk Thistle Veg Capsule for Liver Detox,Supports Liver Detox ",
    qty: "1 Bottle of 500 pellets",
    strikePrice: "845",
    discount: "48% off",
    price: "425",
  },


  {
    id: 3,
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/iujsngvmj0nja3ru0xk9/health-veda-organics-skin-radiance-collagen-builder-veg-capsule.jpg",
    name: "Health Veda Organics Skin Radiance Collagen Builder Veg Capsule",
    qty: "1 Bottle of 500 pellets",
    strikePrice: "799",
    discount: "48% off",
    price: "410",
  }, 
  {
    id: 4,
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/2b1dea512d474ab48100f1969cb9f6e8/tata-1mg-milk-thistle-veg-capsule-for-liver-detox-70-silymarin-with-dandelion-ginger-supports-liver-detox-prevents-fatty-liver.jpg",
    name: "Tata 1mg Milk Thistle Veg Capsule for Liver Detox",
    qty: "1 Bottle of 500 pellets",
    strikePrice: "845",
    discount: "48% off",
    price: "425",
  },

  {
    id: 5,
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/cropped/qslig3kow84ahcdydboo/avene-physiolift-eyes.png",
    name: "Avene Physiolift Eyes",
    qty: "1 Bottle of 500 creame",
    strikePrice: "845",
    discount: "48% off",
    price: "425",
  },

  {
    id: 6,
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/uwq2dwmpqikf9ei3hok5/vaamveda-gorgeous-biotin-tablets-for-hair-growth-with-keratin.jpg",
    name: "Vaamveda Gorgeous Biotin Tablets",
    qty: "1 Bottle of 500 creame",
    strikePrice: "845",
    discount: "48% off",
    price: "425",
  },
  {
    id: 7,
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/cropped/m7ywndnc6att5k6bc8cs/himalaya-liv.-52-ds-tablet.jpg",
    name: "Himalaya Liv. 52 DS Tablet",
    qty: "1 Bottle of 500 creame",
    strikePrice: "845",
    discount: "48% off",
    price: "425",
  },
  {
    id: 8,
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/cropped/yri5iww1npeaibjz6i7y/healthvit-beta-sitosterol-160mg-capsule.jpg",
    name: "HealthVit Beta Sitosterol 160mg Capsule",
    qty: "1 Bottle of 500 creame",
    strikePrice: "845",
    discount: "48% off",
    price: "425",
  },
  {
    id: 9,
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/2b1dea512d474ab48100f1969cb9f6e8/tata-1mg-milk-thistle-veg-capsule-for-liver-detox-70-silymarin-with-dandelion-ginger-supports-liver-detox-prevents-fatty-liver.jpg",
    name: "Tata 1mg Milk Thistle Veg Capsule for Liver Detox",
    qty: "1 Bottle of 500 pellets",
    strikePrice: "845",
    discount: "48% off",
    price: "425",
  },
  {
    id: 10,
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/dj9v8xuxcpfoseulq96n/tata-1mg-coq-10-coenzyme-10-capsules-for-heart-health.jpg",
    name: "Tata 1mg CoQ 10 (Coenzyme 10) Capsules for Heart Health",
    qty: "bottle of 10 gm Tablet",
    strikePrice: "995",
    discount: "35% off",
    price: "444",
  },
  {
    id: 11,
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/images/f_auto,c_fit,q_auto,w_150,h_150/cropped/m7ywndnc6att5k6bc8cs/himalaya-liv.-52-ds-tablet.jpg",
    name: "Himalaya Liv. 52 DS Tablet",
    qty: "1 Bottle of 500 creame",
    strikePrice: "845",
    discount: "48% off",
    price: "425",
  },
]

