export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST";
export const GET_PRODUCT_FAILURE="GET_PRODUCT_FAILURE";
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";


export const ADD_PRODUCT_REQUEST="ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_FAILURE="ADD_PRODUCT_FAILURE";
export const ADD_PRODUCT_SUCCESS="ADD_PRODUCT_SUCCESS";


export const UPDATE_PRODUCT_REQUEST="UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_FAILURE="GET_PRODUCT_FAILURE";
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS";

export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_FAILURE="DELETE_PRODUCT_FAILURE";
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS";



export const GET_ALLUSERS_REQUEST="GET_ALLUSERS_REQUEST";
export const GET_ALLUSERS_FAILURE="GET_ALLUSERS_FAILURE";
export const GET_ALLUSERS_SUCCESS="GET_ALLUSERS_SUCCESS";


export const DELETE_USER_REQUEST="DELETE_USER_REQUEST";
export const DELETE_USER_FAILURE="DELETE_USER_FAILURE";
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";

